### ISSUE TITLE
Install MetalLB in IBM Cloud

### ISSUE THREAD

**Issue by datta-TG** [bitnami/bitnami-docker-metallb-controller#2]
## Pre-requisites

You must have an account created in IBM Cloud. The account needs to either be *Pay-As-You-Go* or *Subscription*. Click [here](https://cloud.ibm.com/docs/account?topic=account-accounts "here") to read more.
If you have a Lite account, you can upgrade it. Click [here](https://cloud.ibm.com/docs/account?topic=account-account-getting-started#account-gs-upgrade "here") to learn how to upgrade.

## Step 1: Provision Kubernetes Cluster

* Click on the search section at the top of the main page, type Kubernetes, and then choose Kubernetes Service.

![Kubernetes1](https://user-images.githubusercontent.com/70336951/105725640-368bd980-5ef7-11eb-931d-4dcc9b578a7f.PNG)

* In the new window, select between the free and standard type under "Pricing plan". Once selected, click on create.

![KubernetesPaid1](https://user-images.githubusercontent.com/70336951/105725655-3c81ba80-5ef7-11eb-8537-e45dcbe45f42.PNG)

We'll choose the Standard Plan for this documentation as the Free Plan may fall short in resources when deploying your pods. We highly recommend using a Standard Plan with the hardware that suits you the best. If you're selecting the Standard Plan, please make sure you select the adequate requirements,

* Select your Kubernetes Version to be the latest available or the required one by your application. In this example, we have set it to be '1.18.13'.
* Select Infrastructure as 'Classic'.
* Leave Resource Group to 'Default'.
* Select Geography to the one that suits you better or that fits your infrastructure.
* Select Availability to be 'Single Zone' or 'Multi Zone' depending on your needs.
* Select a Worker Zone that suits you better or that fits your infrastructure.

![KubernetesPaid2](https://user-images.githubusercontent.com/70336951/105725763-558a6b80-5ef7-11eb-839d-6154d562d547.PNG)

* Select the number of workers in Worker Pool.
* Give your Worker Pool a name.
* Leave the Encrypt Local Disk option 'On'
* Choose 'Both private and public endpoints' on Master Service Endpoint

![KubernetesPaid4](https://user-images.githubusercontent.com/70336951/105725798-5d4a1000-5ef7-11eb-886d-0e59f2a0c108.PNG)

* Give your cluster a name in 'cluster-name'
* Provide the tags to your cluster and click on Create.

![KubernetesPaid5](https://user-images.githubusercontent.com/70336951/105725825-63d88780-5ef7-11eb-9a65-4d69b0d45963.PNG)

Wait a few minutes while your cluster is deployed.

![KubernetesPaid3](https://user-images.githubusercontent.com/70336951/105725849-69ce6880-5ef7-11eb-8739-08ba0b1d5371.PNG)

The following checkmark and the word 'normal' will appear once the Kubernetes Cluster is deployed. You can check it under your cluster section which is located in your *Resources List*.

![KubernetesPaid6](https://user-images.githubusercontent.com/70336951/105725871-6fc44980-5ef7-11eb-91ec-2cc0ffa080ea.PNG)

## Step 2:  Deploy IBM Cloud Block Storage plug-in

* Click on the search section at the top of the main page, select IBM Cloud Block Storage, and click on it.

![Storage1](https://user-images.githubusercontent.com/70336951/105725886-7652c100-5ef7-11eb-99a3-86591896f3e2.PNG)

* A new window opens, select the cluster and enter the name you want for this workspace, in this case, it will be called _storage-example_, accept the terms, click *Install* and wait a few minutes.

![StoragePaid2](https://user-images.githubusercontent.com/70336951/105725927-81a5ec80-5ef7-11eb-89f0-f064d1192563.PNG)

## Step 3: Install MetalLB

* Click on the search section at the top of the main page, type MetalLB, and click on it.

![metal1](https://user-images.githubusercontent.com/70336951/105725945-89fe2780-5ef7-11eb-821b-66e8955095c2.PNG)

*  A new window opens, select the cluster and put the name you want to the workspace, in this case it will be called _metal-example_, accept the terms and click on install. You can modify the different installation parameters at the bottom, like controller and spekaers parameters, in our example we will leave them default, you can read more about the parameters [here](https://cloud.ibm.com/catalog/content/metallb "here").

![metal2](https://user-images.githubusercontent.com/70336951/105725973-8ff40880-5ef7-11eb-8022-b643898377a6.PNG)

## Step 4: Verify Installation

* Go to *Resources List* in the Left Navigation Menu and click on *Kubernetes*.

![test1](https://user-images.githubusercontent.com/70336951/105725996-97b3ad00-5ef7-11eb-86ec-3e9da583332f.png)

* Click the *Actions* button and select *Web terminal*.

![test2](https://user-images.githubusercontent.com/70336951/105726017-9e422480-5ef7-11eb-88c1-ef7a1081098e.PNG)

* A window opens to install the web terminal, click on install and wait a few minutes. The window will pop up at the buttom If the web terminal is already installed.

![test3](https://user-images.githubusercontent.com/70336951/105726040-a4380580-5ef7-11eb-948a-7e7a07be3d02.PNG)

![test7](https://user-images.githubusercontent.com/70336951/105726049-a69a5f80-5ef7-11eb-97e5-abf3c69e9e0c.PNG)

* Once you have installed the terminal, click on the action button again, select web terminal, and type the following command. It will show you the workspaces of your cluster. You can see *metal_example* is now active.

`$ kubectl get ns`

![testmetal1](https://user-images.githubusercontent.com/70336951/105726070-ad28d700-5ef7-11eb-88b3-5d3274207a60.PNG)

* Check the namespace _metal-example_ or the namespace you have specific in namespace, and make sure the pods are running.

  The metallb-controller deployment. This is the cluster-wide controller that handles IP address assignments, you can modify with the controller parameters.

  The metallb-speaker daemonset. This is the component that speaks the protocol(s) of your choice to make the services reachable. You can modify with Speaker parameters.

`$ kubectl get pod -n NAMESERVICE -o wide`

![testmetal2](https://user-images.githubusercontent.com/70336951/105726122-b87c0280-5ef7-11eb-9068-0d272f3e75a8.PNG)

`$ kubectl get service -n NAME SERVICE`

![testmetal3](https://user-images.githubusercontent.com/70336951/105726141-bf0a7a00-5ef7-11eb-85b0-66eb1134a5c4.PNG)

You have finished the installation, enjoy!

**Comment by carrodher** [comment]
Thanks for the info. As it seems that there is no issue we should take action and everything works properly, I am going to mark this issue as “Closed” so it can be used by other users looking for information as if it were documentation
